apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      <parse>
      @type none
      </parse>
      path /home/logs/*
      pos_file /home/logs/backend.application.pos
      path_key filename
      tag backend.application
    </source>
