apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 2
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: jordanovvvv/devops_project:latest
          ports:
            - containerPort: 3000
